[package]
name = "mubah"
version = "0.1.0"
authors = ["TheBreadCat <TheBreadCat@gmail.com>"]
build = "build.rs"

[build-dependencies]
capnpc = "0.3"

[dependencies]
piston_window = "*"
cgmath = "0.2"
piston2d-graphics = "0.4"
rand = "0.3"
capnp = "0.3"
time = "0.1"
